### PR TITLE
Added adt_group, adt_member, and ads_group_table to schema

### PR DESCRIPTION
**Pull request by stancheta**
- I followed the structure of the pgdump in v1

### CODE REVIEW

**Comment by redaikidoka** [comment]
Hmm... do we want to set the owner to 'pol'?

**Comment by stancheta** [comment]
That's how the rest of the schema is currently set up.

**Comment by redaikidoka** [comment]
Hmm.... I bet we probably don't want to do that... what if there's no such user?

**Comment by stancheta** [comment]
A warning pops up and the owner is set to the superuser role (ex. postgres).

**Comment by redaikidoka** [comment]
Neato bandito!

**Comment by redaikidoka** [comment]
Totz workz. Huzzah! :)

**Pull request merged**
